### ISSUE TITLE
Laravel 11 change the path of the {lang}.json file to the root of the project

### ISSUE THREAD

**Issue by xSirLalo** [ctf0/laravel-goto-lang#2]
![laravel8](https://github.com/ctf0/laravel-goto-lang/assets/32373378/e6f1d5f6-25b8-45bb-bdc6-be35b2c7e0e5)
![laravel11](https://github.com/ctf0/laravel-goto-lang/assets/32373378/f7d68b3d-a31d-40a8-a389-c6b1c193a428)

**Comment by ctf0** [comment]
what u need is `laravelGotoLang.defaultPath`
